<template>
	<ul class="w-100 d-flex align-items-center justify-content-center mt-2 gap-2 gap-sm-3 gap-md-4">
		<li class="bg-secondary rounded-2"><PrepTime /></li>
		<li class="bg-secondary rounded-2"><FilterSelect :options="optionsCountry"/></li>
        <li class="bg-secondary rounded-2"><FilterSelect :options="optionsFlavor"/></li>
        <li><PremiumCheck/></li>
	</ul>
</template>

<script setup>
import FilterSelect from "../utils/filterSelect.vue";
import PremiumCheck from "../utils/premiumCheck.vue";
import PrepTime from "../utils/prepTime.vue";

//import { ref } from 'vue';

name: "Filters";

//const props = defineProps({});
//const emits = defineEmits([]);
const optionsFlavor = [
    "Flavor",
    "Salty",
    "Sweet",
    "Acid",
    "Umami",
    "Bitter",
]
const optionsCountry = [
    "Country",
	"Afganistán",
	"Albania",
	"Alemania",
	"Andorra",
	"Angola",
	"Antigua y Barbuda",
	"Arabia Saudita",
	"Argelia",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Azerbaiyán",
	"Bahamas",
	"Bangladés",
	"Barbados",
	"Baréin",
	"Bélgica",
	"Belice",
	"Benín",
	"Bielorrusia",
	"Birmania",
	"Bolivia",
	"Bosnia y Herzegovina",
	"Botsuana",
	"Brasil",
	"Brunéi",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Bután",
	"Cabo Verde",
	"Camboya",
	"Camerún",
	"Canadá",
	"Catar",
	"Chad",
	"Chile",
	"China",
	"Chipre",
	"Ciudad del Vaticano",
	"Colombia",
	"Comoras",
	"Corea del Norte",
	"Corea del Sur",
	"Costa de Marfil",
	"Costa Rica",
	"Croacia",
	"Cuba",
	"Dinamarca",
	"Dominica",
	"Ecuador",
	"Egipto",
	"El Salvador",
	"Emiratos Árabes Unidos",
	"Eritrea",
	"Eslovaquia",
	"Eslovenia",
	"España",
	"Estados Unidos",
	"Estonia",
	"Etiopía",
	"Filipinas",
	"Finlandia",
	"Fiyi",
	"Francia",
	"Gabón",
	"Gambia",
	"Georgia",
	"Ghana",
	"Granada",
	"Grecia",
	"Guatemala",
	"Guyana",
	"Guinea",
	"Guinea ecuatorial",
	"Guinea-Bisáu",
	"Haití",
	"Honduras",
	"Hungría",
	"India",
	"Indonesia",
	"Irak",
	"Irán",
	"Irlanda",
	"Islandia",
	"Islas Marshall",
	"Islas Salomón",
	"Israel",
	"Italia",
	"Jamaica",
	"Japón",
	"Jordania",
	"Kazajistán",
	"Kenia",
	"Kirguistán",
	"Kiribati",
	"Kuwait",
	"Laos",
	"Lesoto",
	"Letonia",
	"Líbano",
	"Liberia",
	"Libia",
	"Liechtenstein",
	"Lituania",
	"Luxemburgo",
	"Madagascar",
	"Malasia",
	"Malaui",
	"Maldivas",
	"Malí",
	"Malta",
	"Marruecos",
	"Mauricio",
	"Mauritania",
	"México",
	"Micronesia",
	"Moldavia",
	"Mónaco",
	"Mongolia",
	"Montenegro",
	"Mozambique",
	"Namibia",
	"Nauru",
	"Nepal",
	"Nicaragua",
	"Níger",
	"Nigeria",
	"Noruega",
	"Nueva Zelanda",
	"Omán",
	"Países Bajos",
	"Pakistán",
	"Palaos",
	"Panamá",
	"Papúa Nueva Guinea",
	"Paraguay",
	"Perú",
	"Polonia",
	"Portugal",
	"Reino Unido",
	"República Centroafricana",
	"República Checa",
	"República de Macedonia",
	"República del Congo",
	"República Democrática del Congo",
	"República Dominicana",
	"República Sudafricana",
	"Ruanda",
	"Rumanía",
	"Rusia",
	"Samoa",
	"San Cristóbal y Nieves",
	"San Marino",
	"San Vicente y las Granadinas",
	"Santa Lucía",
	"Santo Tomé y Príncipe",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leona",
	"Singapur",
	"Siria",
	"Somalia",
	"Sri Lanka",
	"Suazilandia",
	"Sudán",
	"Sudán del Sur",
	"Suecia",
	"Suiza",
	"Surinam",
	"Tailandia",
	"Tanzania",
	"Tayikistán",
	"Timor Oriental",
	"Togo",
	"Tonga",
	"Trinidad y Tobago",
	"Túnez",
	"Turkmenistán",
	"Turquía",
	"Tuvalu",
	"Ucrania",
	"Uganda",
	"Uruguay",
	"Uzbekistán",
	"Vanuatu",
	"Venezuela",
	"Vietnam",
	"Yemen",
	"Yibuti",
	"Zambia",
	"Zimbabue",
];
</script>

<style scoped lang="scss">
// @import "../assets/styles.scss";
li{
    width: 120px;
}
</style>
